# Generated by Django 4.1.3 on 2022-11-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_reviewrating_list_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='developer',
        ),
    ]
