# Generated by Django 4.1.3 on 2022-11-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
