# Generated by Django 4.1.3 on 2022-11-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
    ]
